# Generated by Django 4.2.1 on 2023-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_user_email_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('post', models.CharField(max_length=40, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='static/main/img', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=60, verbose_name='Характеристика')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
            ],
        ),
    ]
