# Generated by Django 4.2.1 on 2023-06-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reviews_alter_form_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
