# Generated by Django 4.2.1 on 2023-06-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
