# Generated by Django 4.2.1 on 2023-06-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image_1', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
                ('image_2', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
                ('image_3', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
                ('image_4', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
                ('image_5', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
                ('image_6', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
                ('image_7', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
                ('image_8', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
                ('image_9', models.ImageField(upload_to='static/main/img', verbose_name='Изображение')),
            ],
        ),
    ]
